name: ksp-lib
description: Fetch stripped KSP libraries
inputs:
  game:
    description: "Name of the game, either ksp or ksp2"
    required: true
  version:
    description: "Version of the game, e.g. 1.12.5"
    required: true
  path:
    description: "Path to extract the contents of the archive into. Defaults to lib/{game}"
    required: false
    default: ""
runs:
  using: composite
  steps:
    - name: download
      run: |
        import urllib.request
        urllib.request.urlretrieve("https://github.com/krpc/ksp-lib/raw/main/${{ inputs.game }}/${{ inputs.game }}-${{ inputs.version }}.zip", "${{ inputs.game }}-${{ inputs.version }}.zip")
      shell: python
    - name: extract
      run: |
        import shutil
        path = "${{ inputs.path }}"
        if len(path) == 0:
            path = "lib/${{ inputs.game }}"
        print("path =", path)
        shutil.unpack_archive("${{ inputs.game }}-${{ inputs.version }}.zip", path)
      shell: python
    - name: cleanup
      run: |
        import os
        os.unlink("${{ inputs.game }}-${{ inputs.version }}.zip")
      shell: python
