name: ci

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-krpc-core-linux:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/krpc/buildenv:3.1.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: fetch
        uses: krpc/krpc-core/.github/actions/bazel-fetch@main
      - name: build
        run: >
          bazel build
            //core:krpc_core
            //tools/TestServer:TestServer
            //tools/ServiceDefinitions:ServiceDefinitions

  build-krpc-core-windows:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: >
          bazel --bazelrc=tools/docker/bazelrc build
            //core:krpc_core
            //tools/TestServer:TestServer
            //tools/ServiceDefinitions:ServiceDefinitions

  build-krpc-core-sln-linux:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/krpc/buildenv:3.1.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: fetch
        uses: krpc/krpc-core/.github/actions/bazel-fetch@main
      - name: deps
        run: bazel build //:csproj
      - name: build
        run: dotnet build KRPC.Core.sln

  build-krpc-core-sln-windows:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: deps
        run: bazel --bazelrc=tools/docker/bazelrc build //:csproj
      - name: build
        run: dotnet build KRPC.Core.sln

  test-krpc-core-linux:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/krpc/buildenv:3.1.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: fetch
        uses: krpc/krpc-core/.github/actions/bazel-fetch@main
      - name: test
        run: bazel test //core:test

  test-krpc-core-windows:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: test
        run: bazel --bazelrc=tools/docker/bazelrc test //core:test
